#!/bin/bash
xautolock -disable
scrot -z /tmp/screenshot.png
convert /tmp/screenshot.png -blur 0x10 /tmp/screenshot.png
playerctl pause
i3lock -i /tmp/screenshot.png -n; $HOME/.config/.myscript//unlock
