#!/bin/bash

xautolock -disable
playerctl status | grep Playing
echo $? > ~/.config/.myscript/tmp
playerctl pause
scrot -z /tmp/screenshot.png
convert /tmp/screenshot.png -blur 0x10 /tmp/screenshot.png
i3lock -f -e -i /tmp/screenshot.png -n; $HOME/.config/.myscript//unlock
