#!/bin/bash

currVol="$(awk -F"[][]" '/dB/ { print $2 }' <(amixer sget Master))"

if [ "$currVol" = "0%" ]; then
    amixer set Master "$(</tmp/volume)"
else
    echo "$currVol" > /tmp/volume
    amixer set Master 0%
fi