#!/bin/bash
xautolock -enable
cat ~/.config/.myscript/tmp | grep 0
if [ $? -eq 0 ]; then
    playerctl play
fi
rm /tmp/screenshot.png
rm ~/.config/.myscript/tmp
feh --randomize --bg-fill --no-xinerama $HOME/.config/Wallpapers/
